name: poker_game
description: Poker game

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.3
  flutter_redux_navigation: ^0.4.1
  cloud_firestore: ^0.12.9+4
  json_annotation: ^3.0.0
  connectivity: ^0.4.4
  redux_thunk: ^0.2.1
  auto_size_text: ^2.1.0
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.14.0+5
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
  test: ^1.6.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.2
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/cards/
  fonts:
    - family: Casino
      fonts:
        - asset: assets/fonts/casino/Casino.ttf
        - asset: assets/fonts/casino/Casino-Italic.ttf
          style: italic
    - family: Casino3DFilledMarquee
      fonts:
        - asset: assets/fonts/casino/Casino3DFilledMarquee.ttf
        - asset: assets/fonts/casino/Casino3DFilledMarquee-Italic.ttf
          style: italic
