name: poker_game
description: Poker game

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.3
  flutter_redux_navigation: ^0.4.1
  cloud_firestore: ^0.12.9+4
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
  test: ^1.6.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.2

flutter:
  uses-material-design: true
